---
title: Квітникарство
timezone: Europe/Kiev
lang: uk

url: http://floriculture.rico.home
baseurl: ''

exclude:
  - Makefile

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
